title: "Alek Spitzer â€“ Senior iOS Engineer"
description: "12+ years building world-class mobile experiences in Swift, SwiftUI, TCA & UIKit."
theme: jekyll-theme-minimal
logo: /assets/images/profile.jpg
show_downloads: false
